FROM mcr.microsoft.com/dotnet/aspnet:10.0  AS base
USER $APP_UID
EXPOSE 8080
EXPOSE 8081

COPY bin/Release/net10.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
RUN dotnet dev-certs https -v -ep openiddict.pfx -p 37ec97e0-64b8-45fe-9b2c-7cce59c754a4
RUN chmod 644 openiddict.pfx

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "Zira.HttpApi.Host.dll"]